name: Notion Jira Consolidator (Full once, then Incremental)

on:
  workflow_dispatch:
    inputs:
      full_scan:
        description: "Force a FULL scan (ignore watermark)?"
        type: boolean
        required: false
        default: false
      force_update_all:
        description: "Force update all rows (ignore Source Hash)?"
        type: boolean
        required: false
        default: false
      max_pages:
        description: "Max pages per run (manual trigger only)"
        required: false
        default: "999999"
  schedule:
    - cron: "7 * * * *"      # hourly incrementals (UTC)

permissions:
  contents: read

concurrency:
  group: jira-notion-sync
  cancel-in-progress: true    # cancel older run when a new one starts

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 600      # allow long full scans
    environment: prod-secrets

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install requests; fi

      - name: Ensure script is present & executable
        run: |
          test -f scripts/sync_jira_notionsrc.py
          chmod +x scripts/sync_jira_notionsrc.py

      # Optional sanity check
      - name: Debug environment vars
        run: |
          echo "Checking secret availability"
          for v in NOTION_TOKEN CONSOLIDATED_DB_ID SYNC_CONTROL_PAGE_ID SOURCE_DB_IDS; do
            if [ -z "${!v}" ]; then echo "::error::$v is empty"; else echo "$v is set ✅"; fi
          done
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          CONSOLIDATED_DB_ID: ${{ secrets.CONSOLIDATED_DB_ID }}
          SYNC_CONTROL_PAGE_ID: ${{ secrets.SYNC_CONTROL_PAGE_ID }}
          SOURCE_DB_IDS: ${{ secrets.SOURCE_DB_IDS }}

      # FULL / MANUAL: only when you press "Run workflow"
      - name: Manual run (with inputs)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          CONSOLIDATED_DB_ID: ${{ secrets.CONSOLIDATED_DB_ID }}
          SYNC_CONTROL_PAGE_ID: ${{ secrets.SYNC_CONTROL_PAGE_ID }}
          SOURCE_DB_IDS: ${{ secrets.SOURCE_DB_IDS }}

          # map inputs → flags
          FORCE_FULL_SCAN: ${{ inputs.full_scan && '1' || '' }}
          FORCE_UPDATE_ALL: ${{ inputs.force_update_all && '1' || '' }}

          # allow overriding max pages via input for manual runs
          MAX_PAGES_PER_RUN: ${{ inputs.max_pages }}
          PAGE_SIZE: '100'
          BATCH_SIZE: '10'
          SLEEP_SECS: '0.4'

          CHECKPOINT_EVERY_PAGE: '1'
          PYTHONUNBUFFERED: '1'
        run: |
          ( while true; do echo "heartbeat $(date -u +%H:%M:%S)"; sleep 60; done ) &
          HB_PID=$!
          stdbuf -oL -eL python -u scripts/sync_jira_notionsrc.py
          RC=$?
          kill $HB_PID || true
          exit $RC

      # SCHEDULED: hourly incrementals
      - name: Incremental (hourly)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          CONSOLIDATED_DB_ID: ${{ secrets.CONSOLIDATED_DB_ID }}
          SYNC_CONTROL_PAGE_ID: ${{ secrets.SYNC_CONTROL_PAGE_ID }}
          SOURCE_DB_IDS: ${{ secrets.SOURCE_DB_IDS }}

          FORCE_FULL_SCAN: ''        # incremental only
          FORCE_UPDATE_ALL: ''       # update only changed rows

          MAX_PAGES_PER_RUN: '800'   # smaller slices = reliable + resumable
          PAGE_SIZE: '100'
          BATCH_SIZE: '10'
          SLEEP_SECS: '0.4'

          CHECKPOINT_EVERY_PAGE: '1'
          PYTHONUNBUFFERED: '1'
        run: |
          ( while true; do echo "heartbeat $(date -u +%H:%M:%S)"; sleep 60; done ) &
          HB_PID=$!
          stdbuf -oL -eL python -u scripts/sync_jira_notionsrc.py
          RC=$?
          kill $HB_PID || true
          exit $RC
